dist: trusty

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - make

compiler:
  - clang
  - gcc

before_install:
  # Install Bazel.
  - wget https://github.com/bazelbuild/bazel/releases/download/0.11.0/bazel_0.11.0-linux-x86_64.deb
  - sudo dpkg -i bazel_0.11.0-linux-x86_64.deb

  # Compile and install Redis.
  - wget https://github.com/antirez/redis/archive/4.0.8.tar.gz
  - tar zxf 4.0.8.tar.gz
  - cd redis-4.0.8
  - make -j4
  - sudo make install
  - cd ..

script:
  # Run the test.
  - bazel build //...
  - bazel test --test_output=all //...
