version: 2
jobs:
  "redis 4":
    working_directory: ~/sessiongate
    docker:
    - image: thulioassis/sessiongate-ci:0.1.0
    steps:
    - checkout:
        path: ~/sessiongate
    - run:
        command: cat /var/versions/redis_4 | xargs /opt/bin/install_redis.sh
    - run:
        command: bazel test --test_output=all //...
  "redis 5":
    working_directory: ~/sessiongate
    docker:
    - image: thulioassis/sessiongate-ci:0.1.0
    steps:
    - checkout:
        path: ~/sessiongate
    - run:
        command: cat /var/versions/redis_5 | xargs /opt/bin/install_redis.sh
    - run:
        command: bazel test --test_output=all //...
workflows:
  version: 2
  build_and_test:
    jobs:
    - redis 4
    - redis 5
